sudo: required
language: bash

services:
  - docker

before_install:
- export TZ='Asia/Kolkata'
- openssl aes-256-cbc -K $encrypted_d2e2b63e72c8_key -iv $encrypted_d2e2b63e72c8_iv -in ./tools/deploy_key.enc -out ./tools/deploy_key -d
- docker pull node:10
before_script:
- eval "$(ssh-agent -s)"
- chmod 600 ./tools/deploy_key
- ssh-add ./tools/deploy_key
- mkdir build
script:
- docker build . -t builder
- docker run -i --rm -v ${PWD}/build:/app/build builder yarn run build:all
after_success:
- cd build
- git init
- git config user.name "Travis CI"
- git config user.email "ci-bot@prasannavl.com"
- git add .
- git commit -m "auto deployment"
- git remote add ghps git@github.com:prasannavl/prasannavl.github.io.git
- git push --force ghps master:master
