sudo: false
language: node_js
node_js:
- '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
  - node_modules
before_install:
- export TZ='Asia/Kolkata'
- openssl aes-256-cbc -K $encrypted_d2e2b63e72c8_key -iv $encrypted_d2e2b63e72c8_iv -in ./tools/deploy_key.enc -out ./tools/deploy_key -d
before_script:
- npm prune
- npm run ready-env
- eval "$(ssh-agent -s)"
- chmod 600 ./tools/deploy_key
- ssh-add ./tools/deploy_key
- mkdir build
script:
- npm run build-static:p
after_success:
- npm run displace-sourcemaps
- cd build
- git init
- git config user.name "Travis CI"
- git config user.email "ci-bot@prasannavl.com"
- git add .
- git commit -m "Auto deployment"
- git remote add ghps git@github.com:prasannavl/prasannavl.github.io.git
- git push --force ghps master:master
